# Generated by Django 3.2.3 on 2021-06-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_notesmedia_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_link', models.CharField(max_length=200)),
                ('n_link_about', models.TextField(max_length=100)),
                ('n_link_id', models.CharField(max_length=50)),
            ],
        ),
    ]
