# Generated by Django 3.2.3 on 2021-06-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionsLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_link', models.CharField(max_length=200)),
                ('s_link_about', models.TextField(max_length=100)),
                ('s_link_id', models.CharField(max_length=50)),
            ],
        ),
    ]
