# Generated by Django 3.2.3 on 2021-05-31 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuesPaper',
        ),
    ]
