# Generated by Django 3.2.3 on 2021-05-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_quespaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='quespaper',
            name='solutions_id',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
